# Generated by Django 3.1 on 2021-05-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_apscheduler', '0008_remove_djangojobexecution_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangojob',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
